# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: accounts-web
    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp
  datasource:
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost/test
        platform: hsqldb
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our ownfghghghjghghgjhjh
error:
  whitelabel:
    enabled:  false
server:
  port: 9090
